// GENERATED by scripts/ingest/build-edge-seed.mjs from supabase/seed/*.json. Do not edit by hand.
import type { SeedApproval, SeedDisease, SeedOrganization } from "./types.ts";

export const DISEASES: SeedDisease[] = [
  {"slug":"dravet","orpha":"ORPHA:33069","mondo":"MONDO:0100135","efo":"MONDO_0100135","name":"Dravet syndrome","name_es":"Síndrome de Dravet","genes":["SCN1A"],"search_terms":["Dravet syndrome","severe myoclonic epilepsy of infancy"],"hgnc":{"SCN1A":"HGNC:10585"},"trial_keywords":["dravet","severe myoclonic epilepsy"]},
  {"slug":"rett","orpha":"ORPHA:778","mondo":"MONDO:0010726","efo":"MONDO_0010726","name":"Rett syndrome","name_es":"Síndrome de Rett","genes":["MECP2"],"search_terms":["Rett syndrome"],"hgnc":{"MECP2":"HGNC:6990"},"trial_keywords":["rett"]},
  {"slug":"cdkl5","orpha":"ORPHA:505652","mondo":"MONDO:0100039","efo":"MONDO_0100039","name":"CDKL5 deficiency disorder","name_es":"Trastorno por deficiencia de CDKL5","genes":["CDKL5"],"search_terms":["CDKL5 deficiency disorder","CDKL5"],"hgnc":{"CDKL5":"HGNC:11411"},"trial_keywords":["cdkl5"]},
  {"slug":"angelman","orpha":"ORPHA:72","mondo":"MONDO:0007113","efo":"MONDO_0007113","name":"Angelman syndrome","name_es":"Síndrome de Angelman","genes":["UBE3A"],"search_terms":["Angelman syndrome"],"hgnc":{"UBE3A":"HGNC:12496"},"trial_keywords":["angelman"]},
  {"slug":"cln2","orpha":"ORPHA:228349","mondo":"MONDO:0008769","efo":"MONDO_0008769","name":"CLN2 disease (late infantile neuronal ceroid lipofuscinosis)","name_es":"Enfermedad CLN2 (lipofuscinosis ceroidea neuronal infantil tardía)","genes":["TPP1"],"search_terms":["CLN2 disease","neuronal ceroid lipofuscinosis 2","Batten disease CLN2"],"hgnc":{"TPP1":"HGNC:2073"},"trial_keywords":["cln2","tpp1","lipofuscinosis type 2","lipofuscinosis 2","late infantile neuronal ceroid"]},
];

export const ORGANIZATIONS: SeedOrganization[] = [
  {"name":"Dravet Syndrome Foundation","country":"US","url":"https://dravetfoundation.org","kind":"patient_org","diseases":["ORPHA:33069"]},
  {"name":"Dravet Syndrome European Federation","country":"EU","url":"https://dravet.eu","kind":"patient_org","diseases":["ORPHA:33069"]},
  {"name":"International Rett Syndrome Foundation","country":"US","url":"https://www.rettsyndrome.org","kind":"patient_org","diseases":["ORPHA:778"]},
  {"name":"Rett Syndrome Research Trust","country":"US","url":"https://reverserett.org","kind":"research","diseases":["ORPHA:778"]},
  {"name":"International Foundation for CDKL5 Research","country":"US","url":"https://www.cdkl5.com","kind":"patient_org","diseases":["ORPHA:505652"]},
  {"name":"Loulou Foundation","country":"UK","url":"https://www.louloufoundation.org","kind":"research","diseases":["ORPHA:505652"]},
  {"name":"Angelman Syndrome Foundation","country":"US","url":"https://www.angelman.org","kind":"patient_org","diseases":["ORPHA:72"]},
  {"name":"Foundation for Angelman Syndrome Therapeutics (FAST)","country":"US","url":"https://cureangelman.org","kind":"research","diseases":["ORPHA:72"]},
  {"name":"Batten Disease Support and Research Association","country":"US","url":"https://bdsrafoundation.org","kind":"patient_org","diseases":["ORPHA:228349"]},
  {"name":"NORD · National Organization for Rare Disorders","country":"US","url":"https://rarediseases.org","kind":"patient_org","diseases":["ORPHA:33069","ORPHA:778","ORPHA:505652","ORPHA:72","ORPHA:228349"]},
  {"name":"EURORDIS · Rare Diseases Europe","country":"EU","url":"https://www.eurordis.org","kind":"patient_org","diseases":["ORPHA:33069","ORPHA:778","ORPHA:505652","ORPHA:72","ORPHA:228349"]},
  {"name":"Buffalo Initiative","country":"US","url":"https://solve.mit.edu/solutions/92088","kind":"research","diseases":["ORPHA:33069","ORPHA:778","ORPHA:505652","ORPHA:72","ORPHA:228349"]},
];

export const APPROVALS: SeedApproval[] = [
  {"orpha":"ORPHA:505652","treatment_id":"CHEMBL1568698","treatment_name":"Ganaxolone","trade_name":"Ztalmy","agency":"FDA","date":"2022-03","published_on":"2022-03-18","indication":"Seizures associated with cyclin-dependent kinase-like 5 (CDKL5) deficiency disorder (CDD) in patients 2 years of age and older","external_id":"FDA:ztalmy-2022","url":"https://www.fda.gov/drugs/news-events-human-drugs/fda-approves-drug-treatment-seizures-associated-rare-disease-patients-two-years-age-and-older","quote":"FDA approves drug for treatment of seizures associated with rare disease in patients two years of age and older","verified":"FDA page headline, date 03/18/2022, brand Ztalmy and indication checked on 2026-10-03; CHEMBL1568698 = GANAXOLONE via Open Targets search"},
];
