/** UI copy for voice surfaces (EN first, ES kept for parity). OWNER: voice lane. */
import type { Locale } from "../i18n";

const en = {
  voice_eleven: "ElevenLabs voice",
  voice_browser: "Browser voice — natural voice unavailable right now",
  captions: "Captions",
  transcript: "Transcript",
  skip_prev: "Previous sentence",
  skip_next: "Next sentence",
  speed: "Speed",
  shortcuts: "Space play/pause · ← → previous/next",
  talk: "Talk to Nexmed",
  talk_mode: (mode: string) => `Talk to the ${mode} guide`,
  connecting: "Connecting…",
  listening: "Listening — go ahead",
  speaking: "Speaking…",
  end: "End",
  mute: "Mute mic",
  unmute: "Unmute mic",
  you: "You",
  agent: "Nexmed",
  mic_denied: "Microphone blocked. Allow it in the browser address bar and try again.",
  error: "The voice connection dropped. Try again.",
  not_configured: "Voice agent not configured yet — narration still works.",
  about: (disease?: string) => (disease ? `Ask about ${disease}` : "Pick a disease, then ask"),
  not_advice: "Not medical advice. Answers come only from cited graph evidence.",
  settings: "Voice settings",
  voice_for: (mode: string) => `Voice for ${mode}`,
  preview: "Preview",
  preview_line: "This is how Nexmed will read verified answers to you.",
  read_answers: "Read every answer aloud",
  close: "Close",
};
export type VoiceCopy = typeof en;

const es: VoiceCopy = {
  ...en,
  voice_eleven: "Voz de ElevenLabs",
  voice_browser: "Voz del navegador — la voz natural no está disponible ahora",
  captions: "Subtítulos",
  transcript: "Transcripción",
  skip_prev: "Frase anterior",
  skip_next: "Frase siguiente",
  speed: "Velocidad",
  shortcuts: "Espacio reproducir/pausar · ← → anterior/siguiente",
  talk: "Hablar con Nexmed",
  talk_mode: (mode) => `Hablar con la guía ${mode}`,
  connecting: "Conectando…",
  listening: "Te escucho",
  speaking: "Hablando…",
  end: "Terminar",
  mute: "Silenciar micrófono",
  unmute: "Activar micrófono",
  you: "Tú",
  mic_denied: "Micrófono bloqueado. Permítelo en la barra del navegador e inténtalo de nuevo.",
  error: "Se cortó la conexión de voz. Inténtalo de nuevo.",
  not_configured: "Agente de voz aún sin configurar — la narración sí funciona.",
  about: (d) => (d ? `Pregunta sobre ${d}` : "Elige una enfermedad y pregunta"),
  not_advice: "No es consejo médico. Las respuestas salen solo de evidencia citada del grafo.",
  settings: "Ajustes de voz",
  voice_for: (mode) => `Voz para ${mode}`,
  preview: "Escuchar",
  preview_line: "Así te leerá Nexmed las respuestas verificadas.",
  read_answers: "Leer cada respuesta en voz alta",
  close: "Cerrar",
};

export const voiceCopy = (l: Locale): VoiceCopy => (l === "es" ? es : en);
