/** UI copy for voice surfaces (EN first, ES kept for parity). OWNER: voice lane. Product name from site.ts. */
import type { Locale } from "../i18n";
import { site } from "../site";

const NAME = site.name;

const en = {
  voice_eleven: "ElevenLabs voice",
  voice_browser: "Browser voice — natural voice unavailable right now",
  captions: "Captions",
  transcript: "Transcript",
  skip_prev: "Previous sentence",
  skip_next: "Next sentence",
  speed: "Speed",
  shortcuts: "Space play/pause · ← → previous/next",
  guide: "Guide",
  guide_title: (mode: string) => `${mode} guide`,
  tab_listen: "Listen",
  tab_talk: "Talk",
  listen_intro: "Hear this route read aloud. Every sentence cites its source; tap a chip to see it on the map.",
  listen_start: "Listen to this route",
  listen_pick: "Pick a disease first — then I can read its route to you.",
  listen_again: "Listen again",
  talk: `Talk to ${NAME}`,
  talk_mode: (mode: string) => `Talk to the ${mode} guide`,
  talk_intro: "Ask out loud. Answers come only from the evidence graph, with sources.",
  connecting: "Connecting…",
  listening: "Listening — go ahead",
  speaking: "Speaking…",
  end: "End",
  mute: "Mute mic",
  unmute: "Unmute mic",
  muted: "Mic muted",
  you: "You",
  agent: NAME,
  unavailable: "Voice isn't available here — use Listen or read the route.",
  mic_denied: "Microphone blocked, so voice isn't available here — use Listen or read the route. To talk, allow the mic in the address bar.",
  no_mic: "No microphone found — use Listen or read the route.",
  error: "The voice connection dropped. Try again, or use Listen.",
  not_configured: "Voice isn't available here — use Listen or read the route.",
  about: (disease?: string) => (disease ? `Ask about ${disease}` : "Pick a disease, then ask"),
  not_advice: "Not medical advice. Answers come only from cited graph evidence.",
  settings: "Voice settings",
  voice_for: (mode: string) => `Voice for ${mode}`,
  preview: "Preview",
  preview_line: `This is how ${NAME} will read verified answers to you.`,
  read_answers: "Read every answer aloud",
  close: "Close",
  see_on_map: "Show on the map",
};
export type VoiceCopy = typeof en;

const es: VoiceCopy = {
  ...en,
  voice_eleven: "Voz de ElevenLabs",
  voice_browser: "Voz del navegador — la voz natural no está disponible ahora",
  captions: "Subtítulos",
  transcript: "Transcripción",
  skip_prev: "Frase anterior",
  skip_next: "Frase siguiente",
  speed: "Velocidad",
  shortcuts: "Espacio reproducir/pausar · ← → anterior/siguiente",
  guide: "Guía",
  guide_title: (mode) => `Guía ${mode}`,
  tab_listen: "Escuchar",
  tab_talk: "Hablar",
  listen_intro: "Escucha esta ruta en voz alta. Cada frase cita su fuente; toca una etiqueta para verla en el mapa.",
  listen_start: "Escuchar esta ruta",
  listen_pick: "Elige primero una enfermedad y te leo su ruta.",
  listen_again: "Escuchar de nuevo",
  talk: `Hablar con ${NAME}`,
  talk_mode: (mode) => `Hablar con la guía ${mode}`,
  talk_intro: "Pregunta en voz alta. Las respuestas salen solo del grafo de evidencia, con fuentes.",
  connecting: "Conectando…",
  listening: "Te escucho",
  speaking: "Hablando…",
  end: "Terminar",
  mute: "Silenciar micrófono",
  unmute: "Activar micrófono",
  muted: "Micrófono silenciado",
  you: "Tú",
  unavailable: "La voz no está disponible aquí — usa Escuchar o lee la ruta.",
  mic_denied: "Micrófono bloqueado, así que la voz no está disponible aquí — usa Escuchar o lee la ruta. Para hablar, permite el micrófono en la barra del navegador.",
  no_mic: "No se encontró micrófono — usa Escuchar o lee la ruta.",
  error: "Se cortó la conexión de voz. Inténtalo de nuevo o usa Escuchar.",
  not_configured: "La voz no está disponible aquí — usa Escuchar o lee la ruta.",
  about: (d) => (d ? `Pregunta sobre ${d}` : "Elige una enfermedad y pregunta"),
  not_advice: "No es consejo médico. Las respuestas salen solo de evidencia citada del grafo.",
  settings: "Ajustes de voz",
  voice_for: (mode) => `Voz para ${mode}`,
  preview: "Escuchar",
  preview_line: `Así te leerá ${NAME} las respuestas verificadas.`,
  read_answers: "Leer cada respuesta en voz alta",
  close: "Cerrar",
  see_on_map: "Ver en el mapa",
};

export const voiceCopy = (l: Locale): VoiceCopy => (l === "es" ? es : en);
