/**
 * Generate supabase/migrations/0013_orphanet_group_aliases.sql from supabase/seed/groups.json:
 *   - disease props.orphanet_groups = [{ orpha, name, synonyms, mondo? }] (read by analyze() to name / alias clusters)
 *   - every group name + synonym becomes a search alias of the disease ("lysosomal storage disease" → Fabry, Gaucher…)
 *   - English display name for the patient_orgs source
 * Set-based and idempotent: props are merged, aliases use ON CONFLICT DO NOTHING.
 *
 *   npx tsx scripts/build-group-aliases.ts
 */
import { readFileSync, writeFileSync } from "node:fs";

interface Group { orpha: string; name: string; synonyms: string[]; mondo?: string }
const groups = JSON.parse(readFileSync("supabase/seed/groups.json", "utf8")) as Record<string, Group[]>;
// Administrative groupings ("potentially indicated for transplant") are not disease classes; "[ambiguous]" synonyms are flagged by MONDO itself.
const ADMIN = /potentially indicated for/i;
const BAD_SYNONYM = /\[ambiguous\]|^obsolete/i;
const slim = Object.fromEntries(Object.entries(groups).map(([k, list]) => [k, list.filter((g) => !ADMIN.test(g.name))
  .map(({ orpha, name, synonyms, mondo }) => ({ orpha, name, synonyms: synonyms.filter((x) => !BAD_SYNONYM.test(x)), ...(mondo ? { mondo } : {}) }))]));
const json = JSON.stringify(slim).replace(/'/g, "''");

const sql = `-- 0013_orphanet_group_aliases.sql — GENERATED by scripts/build-group-aliases.ts from supabase/seed/groups.json.
-- Orphanet classification groups (+ MONDO name/synonyms when Monarch maps that exact Orphanet group) become
-- disease props.orphanet_groups and search aliases, so a class / mechanism query ("lysosomal storage disease")
-- finds its diseases. Idempotent. No deletes.

update public.sources set name = 'Patient organizations (curated, official sites)' where id = 'patient_orgs';

with g as (select key as orpha, value as groups from jsonb_each('${json}'::jsonb))
update public.entities e
   set props = e.props || jsonb_build_object('orphanet_groups', g.groups), updated_at = now()
  from g
 where e.type = 'disease' and e.canonical_id = g.orpha;

insert into public.entity_aliases (entity_id, alias, lang)
select distinct e.id, btrim(a.alias), 'en'
  from public.entities e
  cross join lateral jsonb_array_elements(coalesce(e.props -> 'orphanet_groups', '[]'::jsonb)) as grp
  cross join lateral (select grp ->> 'name' as alias union select jsonb_array_elements_text(coalesce(grp -> 'synonyms', '[]'::jsonb))) as a
 where e.type = 'disease' and char_length(btrim(a.alias)) between 3 and 300
on conflict (entity_id, alias, lang) do nothing;
`;
const outPath = process.argv[2] ?? "supabase/migrations/0013_orphanet_group_aliases.sql"; // applied migrations are never rewritten: pass a new file
writeFileSync(outPath, sql);
console.log(`✔ ${outPath} (${(sql.length / 1024).toFixed(1)} kB): ${Object.keys(groups).length} diseases, ${Object.values(slim).flat().length} disease→group links`);
