/**
 * Compact migration from supabase/seed/regulatory.json (written by scripts/regulatory-links.ts): only the identifiers
 * returned by the APIs travel; SQL builds the URLs (ChEMBL report card, DailyMed set id, Drugs@FDA application).
 *
 *   npx tsx scripts/build-regulatory-migration.ts [out=supabase/migrations/0015_regulatory_links.sql]
 */
import { readFileSync, writeFileSync } from "node:fs";

interface Confirm { orpha: string; source: "fda" | "ema"; external_id: string; url: string; quote: string }
interface Reg {
  chembl: string; links: Record<string, string>; checked_at: string;
  fda?: { set_id: string; brand?: string; application?: string };
  ema?: { product: string; name: string; status: string; conditional: boolean; url: string };
  confirms: Confirm[]; not_confirmed: string[];
}
const out = process.argv[2] ?? "supabase/migrations/0015_regulatory_links.sql";
const reg = Object.values(JSON.parse(readFileSync("supabase/seed/regulatory.json", "utf8")) as Record<string, Reg>);
const day = reg[0]?.checked_at ?? new Date().toISOString().slice(0, 10);
const q = (x: unknown) => `'${JSON.stringify(x).replace(/'/g, "''")}'`;
const clip = (s: string, n: number) => (s.length > n ? s.slice(0, n - 1) + "…" : s);

// [chembl, dailymed set_id, Drugs@FDA application (e.g. NDA209531), FDA brand, EMA url, EMA status, EMA conditional, EMA product]
const rows = reg.filter((r) => r.fda || r.ema).map((r) => [r.chembl, r.fda?.set_id ?? null, r.fda?.application ?? null, r.fda?.brand ?? null, r.ema?.url ?? null, r.ema?.status ?? null, r.ema?.conditional ?? null, r.ema?.product ?? null]);
// [chembl, orpha, source, external_id, quote]   (url rebuilt from the links: DailyMed or the EPAR)
const confirms = reg.flatMap((r) => r.confirms.map((c) => [r.chembl, c.orpha, c.source, c.external_id, clip(c.quote, 180)]));
const checks = reg.flatMap((r) => [
  ...[...new Set(r.confirms.map((c) => c.orpha))].map((o) => [r.chembl, o, `confirmed_by_${[...new Set(r.confirms.filter((c) => c.orpha === o).map((c) => c.source))].sort().join("_")}`]),
  ...r.not_confirmed.map((o) => [r.chembl, o, "not_confirmed_by_label"]),
]);

const sql = `-- 0015_regulatory_links.sql — GENERATED by scripts/build-regulatory-migration.ts from supabase/seed/regulatory.json
-- (scripts/regulatory-links.ts, ${day}). Only API responses: openFDA drug label (DailyMed set id), openFDA Drugs@FDA
-- (application number), EMA medicines JSON export (EPAR url + status), ChEMBL id from Open Targets.
-- 1) treatment props.links + props.regulatory  2) fda / ema evidence on APPROVAL edges whose label / EPAR names the disease
-- 3) regulatory_check on audited APPROVAL edges (source stage kept)  4) medicines_public honours the check. No deletes.

insert into public.sources (id, name, license, base_url) values
  ('ema', 'European Medicines Agency (EPAR)', 'EMA copyright, reuse with attribution', 'https://www.ema.europa.eu')
on conflict (id) do nothing;

-- ChEMBL report card for every treatment whose id comes from ChEMBL (Open Targets)
update public.entities set props = props || jsonb_build_object('links', coalesce(props->'links', '{}'::jsonb)
         || jsonb_build_object('chembl', 'https://www.ebi.ac.uk/chembl/compound_report_card/' || canonical_id || '/')), updated_at = now()
 where type = 'treatment' and canonical_id like 'CHEMBL%';

with r as (select x->>0 chembl, x->>1 set_id, x->>2 appl, x->>3 brand, x->>4 ema_url, x->>5 ema_status, (x->>6)::boolean ema_cond, x->>7 ema_product
             from jsonb_array_elements(${q(rows)}::jsonb) x)
update public.entities e set props = e.props
  || jsonb_build_object('links', coalesce(e.props->'links', '{}'::jsonb) || jsonb_strip_nulls(jsonb_build_object(
       'fda_label', case when r.set_id is not null then 'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=' || r.set_id end,
       'drugs_fda', case when substring(r.appl from '[0-9]+') is not null then 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=' || substring(r.appl from '[0-9]+') end,
       'ema_epar',  r.ema_url)))
  || jsonb_build_object('regulatory', jsonb_build_object('fda_application', r.appl, 'fda_brand', r.brand, 'ema_status', r.ema_status,
       'ema_conditional', r.ema_cond, 'ema_product', r.ema_product, 'checked_at', ${q(day)}::jsonb)), updated_at = now()
  from r where e.type = 'treatment' and e.canonical_id = r.chembl;

insert into public.evidence (edge_id, source_id, external_id, url, quote, retrieved_at)
select ed.id, c->>2, c->>3,
       case when c->>2 = 'fda' then t.props->'links'->>'fda_label' else t.props->'links'->>'ema_epar' end,
       c->>4, now()
  from jsonb_array_elements(${q(confirms)}::jsonb) c
  join public.entities t on t.type = 'treatment' and t.canonical_id = c->>0
  join public.entities d on d.type = 'disease' and d.canonical_id = c->>1
  join public.edges ed on ed.from_id = t.id and ed.to_id = d.id and ed.relation = 'treats'
 where (case when c->>2 = 'fda' then t.props->'links'->>'fda_label' else t.props->'links'->>'ema_epar' end) is not null
on conflict (edge_id, source_id, external_id) do nothing;

update public.edges ed set props = ed.props || jsonb_build_object('regulatory_check', c->>2, 'regulatory_checked_at', ${q(day)}::jsonb), updated_at = now()
  from jsonb_array_elements(${q(checks)}::jsonb) c, public.entities t, public.entities d
 where t.type = 'treatment' and t.canonical_id = c->>0 and d.type = 'disease' and d.canonical_id = c->>1
   and ed.from_id = t.id and ed.to_id = d.id and ed.relation = 'treats';

-- Same columns as 0014; an APPROVAL whose label / EPAR does not name the disease is not counted as approved here.
create or replace view public.medicines_public with (security_invoker = true) as
select
  t.id,
  'treatment:' || t.canonical_id as entity_id,
  t.canonical_id,
  t.name,
  t.props->>'chembl_id'                              as chembl_id,
  t.props->>'drug_type'                              as drug_type,
  t.props->>'mechanism'                              as mechanism,
  coalesce(t.props->'targets', '[]'::jsonb)          as targets,
  coalesce(t.props->'trade_names', '[]'::jsonb)      as trade_names,
  coalesce((t.props->>'approved')::boolean, false)   as approved_anywhere,
  t.props->>'max_stage'                              as max_stage,
  t.props->>'opentargets_url'                        as opentargets_url,
  coalesce(t.props->'links', '{}'::jsonb)            as links,
  bool_or(ed.props->>'stage' = 'APPROVAL' and coalesce(ed.props->>'regulatory_check', '') <> 'not_confirmed_by_label') as approved_for_listed_disease,
  jsonb_agg(distinct jsonb_build_object(
    'disease_id', 'disease:' || d.canonical_id,
    'disease',    d.name,
    'stage',      ed.props->>'stage',
    'status',     ed.props->>'status',
    'regulatory_check', ed.props->>'regulatory_check',
    'nct_ids',    coalesce(ed.props->'nct_ids', '[]'::jsonb),
    'edge_id',    ed.id,
    'sources',    (select coalesce(jsonb_agg(jsonb_build_object('source', ev.source_id, 'url', ev.url, 'external_id', ev.external_id)), '[]'::jsonb)
                   from public.evidence ev where ev.edge_id = ed.id)
  )) as indications
from public.entities t
join public.edges ed   on ed.from_id = t.id and ed.relation = 'treats'
join public.entities d on d.id = ed.to_id and d.type = 'disease'
where t.type = 'treatment'
group by t.id;
`;
writeFileSync(out, sql);
console.log(`✔ ${out}: ${(sql.length / 1024).toFixed(1)} kB · ${rows.length} medicines with FDA/EMA data · ${confirms.length} confirmations · ${checks.length} checks`);
