/**
 * Gene synonyms from HGNC (genenames.org REST): approved name, alias symbols and previous symbols for every gene in
 * the atlas, so "Munc18-1" finds STXBP1. Writes supabase/seed/gene_aliases.json and
 * supabase/migrations/0014_gene_aliases.sql (aliases on live gene entities, matched by HGNC canonical id), and adds
 * the same aliases to data/atlas.json genes (matched by symbol). Never hand-written.
 *
 *   npx tsx scripts/gene-aliases.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import type { AtlasSnapshot } from "../src/lib/atlas/types";

interface GeneAliases { hgnc: string; symbol: string; name: string; aliases: string[] }
// HGNC alias *names* sometimes carry the disease the gene was named after ("Pompe disease" on GAA); as gene aliases
// they would send a disease search to the gene. Symbols of < 4 characters ("p22", "QIN") are too ambiguous to search.
const DISEASE_LIKE = /disease|syndrome|dystroph|hemoglobinuria|leu[ck]odystrophy|lipofuscinosis|deafness|encephalopathy|mucopolysaccharidosis|glycogen storage|epilep|atrophy/i;
const UA = { "user-agent": "nedamex-gene-aliases/1.0", accept: "application/json" };

async function hgnc(symbol: string): Promise<GeneAliases | null> {
  for (let i = 0; i < 3; i++) {
    const r = await fetch(`https://rest.genenames.org/fetch/symbol/${encodeURIComponent(symbol)}`, { headers: UA, signal: AbortSignal.timeout(20_000) }).catch(() => null);
    if (r?.ok) {
      const d = (await r.json())?.response?.docs?.[0];
      if (!d) return null;
      const aliases = [...new Set([d.name, ...(d.alias_symbol ?? []), ...(d.prev_symbol ?? []), ...(d.alias_name ?? [])])]
        .filter((x): x is string => typeof x === "string" && x.length >= 4 && x.toUpperCase() !== symbol.toUpperCase() && !DISEASE_LIKE.test(x));
      return { hgnc: d.hgnc_id, symbol: d.symbol, name: d.name, aliases: aliases.slice(0, 15) };
    }
    await new Promise((res) => setTimeout(res, 600 * (i + 1)));
  }
  return null;
}

async function main() {
  const snap = JSON.parse(readFileSync("data/atlas.json", "utf8")) as AtlasSnapshot;
  const symbols = [...new Set(snap.entities.filter((e) => e.type === "gene").map((e) => String(e.props.symbol ?? e.name)))].sort();
  const out: Record<string, GeneAliases> = {};
  for (const s of symbols) { const g = await hgnc(s); if (g) out[s] = g; await new Promise((res) => setTimeout(res, 120)); }
  writeFileSync("supabase/seed/gene_aliases.json", JSON.stringify(out, null, 2) + "\n");

  // Live DB: gene entities are keyed by HGNC id.
  const rows = Object.values(out).flatMap((g) => g.aliases.map((a) => `(${q(g.hgnc)}, ${q(a)})`));
  const sql = `-- 0014_gene_aliases.sql — GENERATED by scripts/gene-aliases.ts from HGNC (genenames.org): approved name, alias and
-- previous symbols as search aliases of each gene ("Munc18-1" → STXBP1). Idempotent, insert-only.
insert into public.entity_aliases (entity_id, alias, lang)
select e.id, v.alias, 'en'
  from (values ${rows.join(",\n         ")}) as v(hgnc, alias)
  join public.entities e on e.type = 'gene' and e.canonical_id = v.hgnc
on conflict (entity_id, alias, lang) do nothing;
`;
  writeFileSync(process.argv[2] ?? "supabase/migrations/0014_gene_aliases.sql", sql); // applied migrations are never rewritten: pass a new file

  // Bundled snapshot: genes keyed by symbol.
  let added = 0;
  for (const e of snap.entities.filter((x) => x.type === "gene")) {
    const g = out[String(e.props.symbol ?? e.name)]; if (!g) continue;
    e.props.hgnc_id ??= g.hgnc;
    const have = new Set(e.aliases.map((a) => a.alias.toLowerCase()));
    for (const a of g.aliases) if (!have.has(a.toLowerCase())) { e.aliases.push({ alias: a, lang: "en" }); have.add(a.toLowerCase()); added++; }
  }
  writeFileSync("data/atlas.json", JSON.stringify(snap));
  console.log(`✔ ${Object.keys(out).length}/${symbols.length} genes resolved · ${rows.length} live aliases in 0014 · +${added} aliases in data/atlas.json`);
  console.log("  STXBP1:", out.STXBP1?.aliases.join(", "));
}
const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

main().catch((e) => { console.error(e); process.exit(1); });
