/** UI copy for the journey + co-creation surfaces (action lane). English first, Spanish kept in sync. */
import type { Locale } from "@/lib/i18n";

const en = {
  your_route: "Your route",
  route_hint: "Summary first — open any step for the evidence.",
  show_more: "Show the evidence",
  show_less: "Hide",
  inferred_review: "inferred — needs expert review",
  observed: "observed — a source states it",
  extracted: "AI-extracted — needs expert review",
  proposed: "community draft — not evidence",
  needs_review: "Needs expert review",
  why: "Why",
  strategy: "What it means",
  what_differs: "What differs",
  proof: "Proof in the graph",
  this_week: "This week",
  later: "After that",
  owner: { patient_group: "Patient group", researcher: "Researcher", clinician: "Clinician", funder: "Funder" } as Record<string, string>,
  missing_evidence: "Evidence that would change this answer",
  next_question: "Next question to test",
  checked: "What we checked",
  unmet_need: "Unmet need across the cluster",
  unmet_cols: ["Disease", "Approved", "Active trials", "Patient group"],
  cited: "cited",
  evidence_records: "evidence records",
  tenx_cta: "See the 10× route",
  plan_cta: "Printable plan",
  no_route_badge: "Honest answer",
  loading: "Reading the graph…",
  error: "Could not load this journey. The graph view still works.",
  bridges: "bridges both communities",
  enrollment: "enrolls",
  yes: "yes", no: "no",
};

const es: typeof en = {
  your_route: "Tu ruta",
  route_hint: "Primero el resumen — abre cualquier paso para ver la evidencia.",
  show_more: "Ver la evidencia",
  show_less: "Ocultar",
  inferred_review: "inferido — requiere revisión experta",
  observed: "observado — una fuente lo afirma",
  extracted: "extraído por IA — requiere revisión experta",
  proposed: "borrador de la comunidad — no es evidencia",
  needs_review: "Requiere revisión experta",
  why: "Por qué",
  strategy: "Qué significa",
  what_differs: "Qué cambia",
  proof: "Prueba en el grafo",
  this_week: "Esta semana",
  later: "Después",
  owner: { patient_group: "Grupo de pacientes", researcher: "Investigador", clinician: "Clínico", funder: "Financiador" },
  missing_evidence: "Evidencia que cambiaría esta respuesta",
  next_question: "Siguiente pregunta a probar",
  checked: "Qué revisamos",
  unmet_need: "Necesidad no cubierta en el cluster",
  unmet_cols: ["Enfermedad", "Aprobados", "Ensayos activos", "Grupo de pacientes"],
  cited: "citado",
  evidence_records: "registros de evidencia",
  tenx_cta: "Ver la ruta 10×",
  plan_cta: "Plan imprimible",
  no_route_badge: "Respuesta honesta",
  loading: "Leyendo el grafo…",
  error: "No pudimos cargar este recorrido. El grafo sigue funcionando.",
  bridges: "conecta ambas comunidades",
  enrollment: "inscribe",
  yes: "sí", no: "no",
};

export const journeyCopy = { en, es } satisfies Record<Locale, typeof en>;
export type JourneyCopy = typeof en;
