/** UI copy for the journey + co-creation surfaces (action lane). English first, Spanish kept in sync. */
import type { Locale } from "@/lib/i18n";

const en = {
  your_route: "Your route",
  route_hint: "Summary first — open any step for the evidence.",
  show_more: "Show the evidence",
  show_less: "Hide",
  inferred_review: "Inferred · needs expert review",
  observed: "Observed · a source states it",
  extracted: "AI-extracted · needs expert review",
  proposed: "Community draft · not evidence",
  needs_review: "Needs expert review",
  why: "Why",
  strategy: "What it means",
  what_differs: "What differs",
  proof: "Proof in the graph",
  this_week: "This week",
  later: "After that",
  owner: { patient_group: "Patient group", researcher: "Researcher", clinician: "Clinician", funder: "Funder" } as Record<string, string>,
  missing_evidence: "Evidence that would change this answer",
  next_question: "Next question to test",
  checked: "What we checked",
  unmet_need: "Unmet need across the cluster",
  unmet_cols: ["Disease", "Approved", "Active trials", "Patient group"],
  cited: "cited",
  evidence_records: "evidence records",
  tenx_cta: "See the 10× route",
  plan_cta: "Printable plan",
  no_route_badge: "Honest answer",
  loading: "Reading the graph…",
  error: "Could not load this journey. The graph view still works.",
  bridges: "bridges both communities",
  enrollment: "enrolls",
  yes: "yes", no: "no",
  route_sub: "Four questions from your disease to a next step.",
  route_info: "Each answer links to its evidence. Dashed lines are our analysis and need expert review.",
  step_of: (n: number, total: number) => `Step ${n}/${total}`,
  announce: (n: number, total: number, q: string) => `Step ${n} of ${total}: ${q}`,
  back: "Back", next: "Next", finish: "See my route",
  see_evidence: "See evidence",
  more: "Show the details", less: "Hide the details",
  recommendation: (n: number) => `Suggested by Nedamex · based on ${n} sourced records`,
  ready: "Your route is ready",
  ready_sub: "One answer per question — each one opens its evidence.",
  propose_collab: "Propose a collaboration",
  propose_hyp: "Propose a hypothesis",
  add_evidence: "Add missing evidence",
  save_plan: "Save my plan",
  share: "Share link", copied: "Link copied",
  review_steps: "Review the steps",
  groups: (n: number) => `${n} patient ${n === 1 ? "group" : "groups"}`,
  not_advice: "Not medical advice",
  partners: "Suggested partners",
};

const es: typeof en = {
  your_route: "Tu ruta",
  route_hint: "Primero el resumen — abre cualquier paso para ver la evidencia.",
  show_more: "Ver la evidencia",
  show_less: "Ocultar",
  inferred_review: "Inferido · requiere revisión experta",
  observed: "Observado · una fuente lo afirma",
  extracted: "Extraído por IA · requiere revisión experta",
  proposed: "Borrador de la comunidad · no es evidencia",
  needs_review: "Requiere revisión experta",
  why: "Por qué",
  strategy: "Qué significa",
  what_differs: "Qué cambia",
  proof: "Prueba en el grafo",
  this_week: "Esta semana",
  later: "Después",
  owner: { patient_group: "Grupo de pacientes", researcher: "Investigador", clinician: "Clínico", funder: "Financiador" },
  missing_evidence: "Evidencia que cambiaría esta respuesta",
  next_question: "Siguiente pregunta a probar",
  checked: "Qué revisamos",
  unmet_need: "Necesidad no cubierta en el cluster",
  unmet_cols: ["Enfermedad", "Aprobados", "Ensayos activos", "Grupo de pacientes"],
  cited: "citado",
  evidence_records: "registros de evidencia",
  tenx_cta: "Ver la ruta 10×",
  plan_cta: "Plan imprimible",
  no_route_badge: "Respuesta honesta",
  loading: "Leyendo el grafo…",
  error: "No pudimos cargar este recorrido. El grafo sigue funcionando.",
  bridges: "conecta ambas comunidades",
  enrollment: "inscribe",
  yes: "sí", no: "no",
  route_sub: "Cuatro preguntas desde tu enfermedad hasta un siguiente paso.",
  route_info: "Cada respuesta enlaza su evidencia. Las líneas punteadas son nuestro análisis y requieren revisión experta.",
  step_of: (n: number, total: number) => `Paso ${n}/${total}`,
  announce: (n: number, total: number, q: string) => `Paso ${n} de ${total}: ${q}`,
  back: "Atrás", next: "Siguiente", finish: "Ver mi ruta",
  see_evidence: "Ver evidencia",
  more: "Ver los detalles", less: "Ocultar los detalles",
  recommendation: (n: number) => `Sugerido por Nedamex · basado en ${n} registros con fuente`,
  ready: "Tu ruta está lista",
  ready_sub: "Una respuesta por pregunta — cada una abre su evidencia.",
  propose_collab: "Proponer una colaboración",
  propose_hyp: "Proponer una hipótesis",
  add_evidence: "Aportar evidencia que falta",
  save_plan: "Guardar mi plan",
  share: "Compartir enlace", copied: "Enlace copiado",
  review_steps: "Revisar los pasos",
  groups: (n: number) => `${n} ${n === 1 ? "grupo" : "grupos"} de pacientes`,
  not_advice: "No es consejo médico",
  partners: "Socios sugeridos",
};

export const journeyCopy = { en, es } satisfies Record<Locale, typeof en>;
export type JourneyCopy = typeof en;
