/** Co-creation copy (action lane). */
import type { Locale } from "@/lib/i18n";

const en = {
  title: "Co-create",
  actions: { hypothesis: "Propose a hypothesis", collaboration: "Propose a collaboration", evidence: "Add missing evidence" },
  kind_label: "Kind of draft",
  draft_note: "This is a draft. It is shown as a ghost in the graph and never counts as evidence until an expert reviews it.",
  field_title: "Title",
  field_body: "Draft",
  cited_edges: "Evidence it builds on",
  no_edges: "No cited edges — it will be shown as an open question.",
  remove: "Remove",
  contact_legend: "Contact (optional)",
  consent: "I agree that Nedamex stores this contact so a reviewer can follow up. It is never shown publicly.",
  contact_placeholder: "Email or organization contact",
  submit: "Save draft",
  saving: "Saving…",
  cancel: "Cancel",
  error: "Could not save",
  saved_shared: "Draft saved to the shared community drafts.",
  saved_local: "Saved locally (demo) — the shared drafts database is not live yet.",
  toast_detail: "It now appears in the graph as a dashed “community draft”, not as evidence.",
  drafts_title: "Community drafts for this disease",
  drafts_count: "drafts",
  stored_local: "saved locally (demo)",
  stored_shared: "shared",
  disclaimer: "Not medical advice. Drafts are hypotheses for experts to test.",
  partners: "Suggested partners",
  partners_hint: "Ranked by shared mechanism, shared researchers/sponsors and active studies.",
  reasons: "Why",
  propose_with: "Propose a collaboration",
  draft_intro: "Draft an intro message",
  copy: "Copy",
  copied: "Copied",
  intro_title: "Intro message (draft)",
  intro_note: "Templated from the graph — every claim lists its source. Review before sending.",
  polished: "Wording polished by AI; citations kept.",
  templated: "Template (no AI).",
  open_mail: "Open in email",
};

const es: typeof en = {
  title: "Co-crear",
  actions: { hypothesis: "Proponer una hipótesis", collaboration: "Proponer una colaboración", evidence: "Aportar evidencia que falta" },
  kind_label: "Tipo de borrador",
  draft_note: "Es un borrador. Se muestra como fantasma en el grafo y nunca cuenta como evidencia hasta que lo revise un experto.",
  field_title: "Título",
  field_body: "Borrador",
  cited_edges: "Evidencia en la que se apoya",
  no_edges: "Sin aristas citadas — se mostrará como pregunta abierta.",
  remove: "Quitar",
  contact_legend: "Contacto (opcional)",
  consent: "Acepto que Nedamex guarde este contacto para que un revisor dé seguimiento. Nunca se muestra en público.",
  contact_placeholder: "Correo o contacto de la organización",
  submit: "Guardar borrador",
  saving: "Guardando…",
  cancel: "Cancelar",
  error: "No se pudo guardar",
  saved_shared: "Borrador guardado en los borradores compartidos de la comunidad.",
  saved_local: "Guardado localmente (demo) — la base de borradores compartidos aún no está activa.",
  toast_detail: "Ahora aparece en el grafo como “borrador de la comunidad” punteado, no como evidencia.",
  drafts_title: "Borradores de la comunidad para esta enfermedad",
  drafts_count: "borradores",
  stored_local: "guardado localmente (demo)",
  stored_shared: "compartido",
  disclaimer: "No es consejo médico. Los borradores son hipótesis para que las prueben expertos.",
  partners: "Socios sugeridos",
  partners_hint: "Ordenados por mecanismo compartido, investigadores/patrocinadores en común y estudios activos.",
  reasons: "Por qué",
  propose_with: "Proponer una colaboración",
  draft_intro: "Redactar un mensaje de presentación",
  copy: "Copiar",
  copied: "Copiado",
  intro_title: "Mensaje de presentación (borrador)",
  intro_note: "Plantilla a partir del grafo — cada afirmación lista su fuente. Revísalo antes de enviarlo.",
  polished: "Redacción pulida por IA; citas conservadas.",
  templated: "Plantilla (sin IA).",
  open_mail: "Abrir en el correo",
};

export const coCopy = { en, es } satisfies Record<Locale, typeof en>;
